### ISSUE TITLE
builder.addDataSet(IDataSet dataSet)

### ISSUE THREAD

**Issue by mab** [marcphilipp/dbunit-datasetbuilder#3]
Hello,

I think builder.addDataSet(IDataSet dataSet) would be a nice method. I have some tests where this would help.

Yours,
Matthias.

**Comment by mab** [comment]
Currently I get not through the company proxy, so I'll post a pull request tonight. 

```
public void add(final IDataSet dataSet) throws DataSetException {
    final IDataSet[] dataSets = { build(), dataSet };
    final CompositeDataSet composite = new CompositeDataSet(dataSets);
    this.dataSet = new CachedDataSet(composite);
    consumer = new BufferedConsumer(this.dataSet);
}
```

**Comment by marcphilipp** [comment]
Looks like a good feature to add. Before submitting a pull request, please remove those final modifiers.

**Comment by mab** [comment]
Ok. They come with my autosave actions. I'll change that.

**Comment by mab** [comment]
See #4
